CC = gcc
FLAGS = -L../../ -lmlx -framework OpenGL -framework AppKit -D BUFFER_SIZE=30 -g
SRCS = *.c ../../../get_next_line/*.c ../../../libft/*.c
MAP_NAME = map.cub

all : 
	$(CC) $(FLAGS) $(SRCS) $(MAP_NAME)
	./a.out